print("Para descobrir sua idade em idade de cachorro digite sua idade abaixo: ")
idade=input()
idade=int(idade)
idadedecachorro=(idade*7)
print("Se voce fosse um cachorro voce teria", idadedecachorro," anos!")
print("'0'____'")
print("      | | | |")