print("Digite um número que você queira somar e multiplicar com o próximo número,dê enter após digitar o primeiro número")
numero1=input()
numero1=int(numero1)
print("Escreva agora o segundo número")
numero2=input()
numero2=int(numero2)
print("Agora aqui a soma e a multiplicaçao desses números, respectivamente:")
print(" SOMA-",numero1+numero2,)
print(" MULTIPLICAÇÃO-",numero1*numero2,)
