print("Digite seu volume atual e depois seu volume desejado para saber a diferença de volume, para regular o volume do seu dispositivo de som:")
volumeatual=input()
volumeatual=int(volumeatual)
print("Agora digite o volume desejado:")
volumedesejado=input()
volumedesejado=int(volumedesejado)
print("A diferença de volume é:",volumedesejado-volumeatual)