print("Um menino empinando pipa")
print("    /\                                                         ")
print("    \/ \                               |_._|		 	  ")
print("    -)-  \                            __|_____	  ")
print("   -(-     \                          |  #      #   |	  ")
print("    -)-      \                        |  #      #   |	  ")
print("                \                      |  #      #   |	  ")
print("                  \   0               |  #      #   |      ")
print("                    \/|\              |               |	  ")
print("_________ /\______|__[_]__|__ ")
print(" ____          ____          ____          _ ")