print("Aqui vai um dinossauro!")
print("                                     ___     ")
print("                                   /     _ )   ")
print("                      .-^^^-/     /        ")
print("               __/                /         ")
print("             ⟨__ .|_|----|_|           ")
print("                                               ")
print("E aqui vai um bolo! hummmmmm")
print("	¡"*10)
print("  #"*21)
print("  ="*21)
print("  #"*21)
print("  ="*21)
print("  #"*21)